const mongoose = require("mongoose");

const doctorSchema = new mongoose.Schema({
  firstName: { type: String, required: true },
  lastName: { type: String, required: true },
  phone: { type: String, required: true },
  whatsappNumber: { type: String },
  email: { type: String, required: true, unique: true },
  dob: { type: Date, required: true },
  gender: { type: String, required: true },
  profilePhoto: { type: String },
  medicalRegNumber: { type: String, required: true },
  degrees: [{ degree: String, otherDegree: String }],
  yearsOfExperience: { type: Number },
  specialization: { type: String, required: true },
  subSpecialization: { type: String },
  additionalCertifications: [{ type: String }],
  medCouncilCert: { type: String },
  currentWorkplaces: [{ type: String }],
  clinicDetails: [{ name: String, address: String, yearsOfStay: Number }],
  workSchedule: [{ day: String, timeSlots: [String] }],
  consultationModes: [{ type: String }],
  languagesSpoken: [{ type: String }],
  otherLanguages: { type: String },
  consultationFeeOnline: { type: Number },
  consultationFeeOffline: { type: Number },
  feeVariesByComplexity: { type: Boolean, default: false },
  feeVariationDetails: { type: String },
  emergencyAvailability: { type: Boolean, default: false },
  availability24_7: { type: Boolean, default: false },
  onCallConsultation: { type: Boolean, default: false },
  onCallHours: { type: String },
  maxPatientsPerDay: { type: Number },
  followUpDiscount: { type: Boolean, default: false },
  followUpDiscountPercentage: { type: Number },
  referralProgram: { type: Boolean, default: false },
  referralCode: { type: String },
  connectedHospitalDatabase: { type: Boolean, default: false },
  hospitalDatabaseDetails: { type: String },
  medicalRecordAccess: { type: Boolean, default: false },
  medicalRecordAccessDetails: { type: String },
  allowPatientReviews: { type: Boolean, default: false },
  publicProfileVisibility: { type: Boolean, default: false },
  medicalLicense: { type: String },
  digitalSignature: { type: String },
  idProof: { type: String },
  agreementConsent: { type: Boolean, required: true },
  bankDetails: {
    name: { type: String },
    accountNo: { type: String },
    ifscCode: { type: String },
  },
  upiId: { type: String },
  paymentModesAccepted: [{ type: String }],
  preferredCommunication: { type: String },
  remarksForAdmin: { type: String },
  createdAt: { type: Date, default: Date.now },
  updatedAt: { type: Date, default: Date.now },
});

module.exports = mongoose.model("DoctorProfile", doctorSchema);
